### ISSUE TITLE
Update buildroot for compatibility with glibc 2.27+

### ISSUE THREAD

**Issue by alehed** [enclustra-bsp/busybox-rootfs#2]
As reported in enclustra-bsp/bsp-xilinx#6, builds fail in Ubuntu 18.04. This is caused by an outdated e2fsprogs (pre v1.43.8). Please consider upgrading to buildroot 2018.2 or later which contains a compatible version.

Next week with the release of 18.04.1, 16.04 users are going to be prompted to upgrade to Ubuntu 18.04 for the first time so a larger number of migrations can be expected.

**Comment by tgorochowik** [comment]
Buildroot has been bumped, thanks!
